### ISSUE TITLE
[Feature Request] Add useStore composable with Magento 2 multistore feature

### ISSUE THREAD

**Issue by alefbarbeli** [vuestorefront/magento2#113]
Magento Documentation on "Multistore":
https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html

We should implement `useStore` feature from core, taking advantage of Magento "Multistore" feature.

**Describe the solution you'd like**
The Multistore feature allow merchants to use a single Magento installation and admin to rule multiple stores/ catalogs/ currencies

**Comment by alefbarbeli** [comment]
Issue started.

**Comment by bloodf** [comment]
It need to be developed alongside this issue https://github.com/vuestorefront/magento2/issues/194
