### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Smpatidar** [vuestorefront/magento2#1145]
### Expected Behavior

when i run my storefront on url ( server ) it will work fine

### Actual Behavior

when i run command  "yarn dev"  it show me running on my IP address like " listing : http://192.168.3.205:5000/ "
its work perfectly fine when i check it on IP 
but when i check it on URL it is not working  like customer cannot login, add to cart is not working 
i don't understand what is happening  it is fresh project i just add line of code in env file only please have a look and suggest me what i am doing wrong 
![Screenshot from 2022-06-20 17-47-12](https://user-images.githubusercontent.com/102517004/174601298-1387195d-05f2-4a2f-93a4-17651d0227bc.png)

### Steps to reproduce

1. my running url is "https://vuestore.24livehost.com" (as i m running old vuejs project this url )
2. it is bind on 5000 port
3. i download and install fresh project and change  .env  file according to screenshot 
4. when i hit  url in  ip mode like "http://192.168.3.118:5000/" is working fine
5. but when i hit above url  addtocart like  many post request is not working

### What version of Magento 2 integration are you using?

magento 2.4.4

### What version of Node.js are you using?

16 (lts)

### What browser (and version) are you using?

chrome and firefox

### What operating system (and version) are you using?

ubuntu

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Smpatidar** [comment]
> Hi, @Smpatidar, please add steps to reproduce, then we will take a look.

please check

**Comment by Frodigo** [comment]
Please try to add this to the nuxt.config:

```
publicRuntimeConfig: {
    middlewareUrl: 'https://api.example.com' // your domain here
}
```

Reference: https://docs.vuestorefront.io/v2/architecture/server-middleware.html#separating-server-middleware-from-nuxt-js

**Comment by Smpatidar** [comment]
> Please try to add this to the nuxt.config:
> 
> ```
> publicRuntimeConfig: {
>     middlewareUrl: 'https://api.example.com' // your domain here
> }
> ```
> 
> Reference: https://docs.vuestorefront.io/v2/architecture/server-middleware.html#separating-server-middleware-from-nuxt-js

// nuxt.config.js
export default {
modules: [

    '@vue-storefront/middleware/nuxt'
    ],

    publicRuntimeConfig: {
    middlewareUrl: 'https://vuestore.24livehost.com/'
    }
    }

i add this it give me error and my development server is exit with many error

**Comment by sequensucks** [comment]
@Smpatidar its a way for api. You need to add 
publicRuntimeConfig: {
   middlewareUrl: 'https://vuestore.24livehost.com/api'
}

**Comment by Smpatidar** [comment]
> @Smpatidar its a way for api. You need to add publicRuntimeConfig: { middlewareUrl: 'https://vuestore.24livehost.com/api' }

Thank you so much 
i am feeling blessed
