### ISSUE TITLE
[ROADMAP] Magento 2 - VueStorefront 2 (Stable)

### ISSUE THREAD

**Issue by bloodf** [vuestorefront/magento2#116]
# ROADMAP IS NOW ON THE PROJECTS TAB!!!

https://github.com/vuestorefront/magento2/projects/5

**Comment by tafelnl** [comment]
Thanks for sharing your roadmap! I would like to add to this, the fact that the docs and template should also be updated. They are now incomplete and not up-to-date.

**Comment by bloodf** [comment]
> Thanks for sharing your roadmap! I would like to add to this, the fact that the docs and [template](https://github.com/vuestorefront/template-magento) should also be updated. They are now incomplete and not up-to-date.

The template is always updated when a release is made, so there aren't any different from the master to the current template :), if you find a difference, please open a PR so we can fix it :)

The docs I know it's not updated. I'm seeking people to help me with this. If you want to join and help document the project I will be flattered
