### ISSUE TITLE
[Bug]: add product to cart (loop infinity) and set billing address on cart (not working)

### ISSUE THREAD

**Issue by DaiLoc5698** [vuestorefront/magento2#126]
### Contact Details

dailoc.lq@gmail.com

### add product to cart not working (loop infinity)

<img width="904" alt="Screen Shot 2021-08-06 at 10 21 58" src="https://user-images.githubusercontent.com/76195735/128451985-4746fd3e-5daa-4d0b-8af0-ed40180f1b29.png">

### set billing address on cart not working

<img width="772" alt="Screen Shot 2021-08-06 at 10 32 43" src="https://user-images.githubusercontent.com/76195735/128452045-9cdd4a71-88f4-42b3-a1c4-e80db929c914.png">

### solution to fix set billing address on cart
 ```
save: async (context: Context, params) => {
    Logger.debug('[Magento] setBillingAddress');
    const { id } = context.cart.cart.value;
    Logger.debug(id);
    Logger.debug(typeof id);
    const {
      apartment,
      sameAsShipping,
      ...address
    } = params.billingDetails;

    const setBillingAddressOnCartInput: SetBillingAddressOnCartInput = {
      cart_id: id,
      billing_address: {
        address: {
          ...address,
          street: [address.street, apartment],
        },
        same_as_shipping: sameAsShipping,
      },
    };

    const { data } = await context.$magento.api.setBillingAddressOnCart(setBillingAddressOnCartInput);

    /**
     * This is a workaround needed due to Magento GraphQL API
     * cleaning the Shipping method after defining the billing address
     */
    const shippingMethod = context.useShippingProvider.state.value;

    await context.useShippingProvider.save({
      shippingMethod: {
        carrier_code: shippingMethod.carrier_code,
        method_code: shippingMethod.method_code,
      },
    });
    /**
     * End of GraphQL Workaround
     */

    return data.setBillingAddressOnCart.cart.billing_address;
  },
```

### Steps to reproduce

1.  sign in
2. sign out
3. sign in again (now vsf-cartId not generate)
4. add product to cart (not working)
5. in checkout, set billing address on cart (not working)

### Version

1.0.0-rc.2

### What browsers are you seeing the problem on?

Chrome

### What node version you were using?

14.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
fixed in PR #122
