### ISSUE TITLE
[Bug]: add product to cart not working after place order

### ISSUE THREAD

**Issue by DaiLoc5698** [vuestorefront/magento2#130]
### Contact Details

dailoc.lq@gmail.com

### loop infinity

<img width="772" alt="Screen Shot 2021-08-11 at 17 54 28" src="https://user-images.githubusercontent.com/76195735/129017325-b53da202-252b-40af-ad5a-364930914c2d.png">

### Steps to reproduce

1. login
2. add product to cart
3. place oder
4. add product to cart

### Version

1.0.0-rc.2

### What browsers are you seeing the problem on?

Chrome

### What node version you were using?

14.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
I will look into that @DaiLoc5698
