### ISSUE TITLE
[Bug]: Product price is not updated on variant selection

### ISSUE THREAD

**Issue by zfmaster** [vuestorefront/magento2#133]
### Expected Behavior

For configurable product price should be updated on variant selection according to price setting for variant

### Actual Behavior

It's always displayed price of cheapest variant

### Possible Solution

The prices for variants are queried from M2 graphql:

```      
... on ConfigurableProduct {
        variants {
          product {
            id
            name
            sku
            price_range{
              minimum_price{
                regular_price{
                  value
                  currency
                }
              }
            }
          }
        }
      }
```
It's not implemented atm in vuestorefront/magento2

### Steps to reproduce

1. Find configurable product with different prices for variant (I prepared testing environment with clean M2 v2.4.3 and sample data, here is the product fits conditions: https://vsf-magento.mediabridge.solutions/eos-v-neck-hoodie.html )
2. Select variants with different price on standard M2 FE (for example product it's different colors of XL size). Observe price changed
3. Select variants with different price on VSF (here is same product: https://vsf.mediabridge.solutions/p/WH11/eos-v-neck-hoodie.html  ). Observe price is not changed.

### What version of Magento 2 integration are you using?

develop

### What version of Node.js are you using?

14.17.4

### What browser (and version) are you using?

Chrome, FF

### What operating system (and version) are you using?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
@zfmaster thanks for the information, I will add this on the Bugs to be fixed on the [Roadmap](https://github.com/vuestorefront/magento2/projects/5)

**Comment by zfmaster** [comment]
Fixed in https://github.com/vuestorefront/magento2/pull/143
