### ISSUE TITLE
[Feature]: Add custom headers

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#1364]
### How the project can be improved?

Need to implement the ability to add custom headers to queries and mutations.

For example, i want to enable this feature
[Need to implement the ability to add custom headers to queries and mutations.](https://devdocs.magento.com/guides/v2.4/graphql/protected-mutations.html)

And i need to add 2 custom headers for a create customer mutation.

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bartoszherba** [comment]
Done in https://github.com/vuestorefront/magento2/pull/1365
