### ISSUE TITLE
Docker runtime variables versus build time

### ISSUE THREAD

**Issue by drew-webscale** [vuestorefront/magento2#1367]
### What is your question / Please describe your issue

I have been working with the Vue Storefront code and Docker for a few months now and I think the latest version is causing me some issues when it comes to environment variables and that the issue might be related to the newest version. Before I submit a bug I wanted to make sure I understand how environment variables work with Vue Storefront and Docker.

I've noticed recently that my environment variables only seem to work if I set them during build time with Docker. If I mount in a .env file to a running Docker image or import the environment variables file the Vue storefront doesn't seem to read them properly. If I include a .env during build then everything seems to work okay. Should I be able to inject environment variables at run-time and have it work or do they need to be at build time?

### What version of Magento 2 Integration are you using?

1.0.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bartoszherba** [comment]
@drew-webscale you can set variables only on the build time, ot be more accurate, whatever is the context you run the app in, it must contains variables when you start the app. It has nothing to do with vsf.
But if you can stop the app in the running container without closing its process and restart it with new env then it will work. I assume you are talking about image to run app which will stop once the app stop to work.

`Should I be able to inject environment variables at run-time and have it work or do they need to be at build time?`
No, you can't inject variables that are use on the build-time to setup project.

**Comment by bartoszherba** [comment]
I close the issue due to inactivity.
