### ISSUE TITLE
[Bug]: Pagination on product list pages is broken

### ISSUE THREAD

**Issue by zfmaster** [vuestorefront/magento2#138]
### Expected Behavior

Pagination on product list page (for example category page) works fine

### Actual Behavior

Links in pagination bar looks like https://vsf.mediabridge.solutions/c/[object%20Object] , what produces error on pagination switch

### Possible Solution

- After investigation it was found the bug is produced by changes in Storefront-UI: https://github.com/vuestorefront/storefront-ui/commit/253a30f9944b58d39893ff6d4a20e492466a9477
- This changes were reverted: https://github.com/vuestorefront/storefront-ui/issues/1883
- But storefront-ui is not updated to version it's fixed because of wrong release version (the fix is in 0.10.8, but broken is 0.10.71 which is bigger)
- The bugreport is left on storefront-ui page: https://github.com/vuestorefront/storefront-ui/issues/1952
- This bug report is created for documentation and next steps. If https://github.com/vuestorefront/storefront-ui/issues/1952 will be resolved fast by storefront-ui team no more actions are required from our side, otherwise we would need to update stroefront-ui library version in package.json (to be > 0.10.7 and < 0.10.71)

### Steps to reproduce

1. Open category page (ex. https://vsf.mediabridge.solutions/c/women.html )
2. Click page numbers in pagination bar
3. Observe

### What version of Magento 2 integration are you using?

2.4.3

### What version of Node.js are you using?

14.17.4

### What browser (and version) are you using?

Chrome, FF

### What operating system (and version) are you using?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
Added to roadmap
