### ISSUE TITLE
[Bug]: Not all subcategories and products are loaded

### ISSUE THREAD

**Issue by zfmaster** [vuestorefront/magento2#139]
### Expected Behavior

When VSF is connected to sample M2 data the categories and products in categories are loaded like on M2 FE ( https://vsf-magento.mediabridge.solutions/women.html ) or like on VSF1 demo ( https://capybara.storefrontcloud.io/women.html, https://demo.vuestorefront.io/women.html )

### Actual Behavior

Some categories are displayed, but their subcategories and products inside are not loaded. Instead products and subcategories from other categories are displayed: https://vsf.mediabridge.solutions/c/women.html

### Possible Solution

Not clear yet what produces such behavior and how to fix it. Still in investigation process. 

The reason could be way how products are assigned to categories in M2: if product is assigned to subcategory it does not automatically means it's also belongs to main category. 

![Selection_065](https://user-images.githubusercontent.com/10129233/129366801-23fa0235-484d-4e04-950f-cc2f84a11f66.png)

### Steps to reproduce

1. Open demo shop connected to Magento 2 sample data 
2. Click 'Women' or 'Men' category ( https://vsf.mediabridge.solutions/c/women.html )
3. Observe products
4. Observe subcategories in left sidebar

### What version of Magento 2 integration are you using?

2.4.3

### What version of Node.js are you using?

14.17.4

### What browser (and version) are you using?

Chrome, FF

### What operating system (and version) are you using?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
added to roadmap
