### ISSUE TITLE
[Bug]: cart and checkout ignore selected currency

### ISSUE THREAD

**Issue by JesseMaxwell** [vuestorefront/magento2#1407]
### Expected Behavior

Cart shows the correct currency symbol _and_ the correct amount based on the chosen currency. 

### Actual Behavior

The cart (and checkout) show the correct currency symbol but the _wrong_ amount. In the screenshot below, INR was the previously chosen currency. The amount show is the INR amount even though the currency symbol shows USD. This works in the reverse as well. 

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/30010447/209881363-ba7f9380-1dbc-4377-acde-b70e892ce3e7.png">

### Possible Solution

The cart and checkout should request prices in the selected currency.

### Steps to reproduce

1. Browse to product.
2. Add product to cart
3. Change currency

### What version of Magento 2 integration are you using?

1.0.2

### What version of Node.js are you using?

16.13.1

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bartoszherba** [comment]
Hello, @JesseMaxwell What is the currency exchange rate that you have configured in Magento?

**Comment by JesseMaxwell** [comment]
81.3825 right now for INR but the currency symbol is mostly the problem

**Comment by JesseMaxwell** [comment]
You are right; this is on my side. Thank you!

**Comment by bartoszherba** [comment]
Thank you for engagement and have a nice day!
