### ISSUE TITLE
[Bug]: Shipping price is not applyed to order total price

### ISSUE THREAD

**Issue by zfmaster** [vuestorefront/magento2#144]
### Expected Behavior

When order is created shipping price is added to order and displayed on order totals
![Selection_079](https://user-images.githubusercontent.com/10129233/129952592-b103908c-2ca5-43da-8631-0dde54ecdecc.png)

### Actual Behavior

1. - Order totals are displayed without shipping price :x:
2. - Shipping price is send to M2 right :heavy_check_mark:
3. - Order total is sent to M2 wrong (and will have influence on payment) :x:
![Selection_078](https://user-images.githubusercontent.com/10129233/129952634-18c28f52-d2be-40ae-888a-1399b44fc4c5.png)
![Selection_080](https://user-images.githubusercontent.com/10129233/129952642-99f4ad7f-0360-4b20-984f-7c2f544c476e.png)
![Selection_081](https://user-images.githubusercontent.com/10129233/129952777-940a3909-da76-4ab6-a54d-1011a29ab63c.png)

### Steps to reproduce

1. Add product to basket
2. Proceed to checkout
3. Select shipping with price 
4. Proceed to order summary page
5. Observe

### What version of Magento 2 integration are you using?

2.4.3

### What version of Node.js are you using?

14.17.4

### What browser (and version) are you using?

Chrome, FF

### What operating system (and version) are you using?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
Added to Roadmap

**Comment by zfmaster** [comment]
Fixed in https://github.com/vuestorefront/magento2/pull/171
