### ISSUE TITLE
[Bug]: Discount is displayed wrong on checkout step 

### ISSUE THREAD

**Issue by zfmaster** [vuestorefront/magento2#145]
### Expected Behavior

Discount is displayed like on M2 FE:
![Selection_082](https://user-images.githubusercontent.com/10129233/129954220-e1006368-375d-422a-a143-5be0934a99ee.png)

### Actual Behavior

Discount is not displayed in basket overlay
Discount is displayed wrong on order summary page

![Selection_084](https://user-images.githubusercontent.com/10129233/129953817-bbd54aac-fc23-4173-b26e-88a0d5780cbe.png)
![Selection_083](https://user-images.githubusercontent.com/10129233/129953819-7dab54b5-9700-4032-8c65-59a9c45ff790.png)

### Steps to reproduce

1. Pick up product with discount (for example this product https://vsf.mediabridge.solutions/p/WH11/eos-v-neck-hoodie.html has discount if qty >= 4 )
2. Add necessary quantity to basket
3. Observe basket overlay
4. Navigate to checkout 
5. Observe checkout summary page

### What version of Magento 2 integration are you using?

develop

### What version of Node.js are you using?

14.17.4

### What browser (and version) are you using?

Chrome, FF

### What operating system (and version) are you using?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
Good point!

This needs to be fixed before stable!
