### ISSUE TITLE
[Feature]: Do not create an empty cart automatically

### ISSUE THREAD

**Issue by jonathanribas** [vuestorefront/magento2#147]
### How the project can be improved?

Actually when you access VSF2 it automatically creates an empty cart.

Most users and bots only visit pages and don't perform an add to cart action at all. Why flood M2 database with empty carts all the time?

Cart should only be created when a product is added to the cart.

### What are the acceptance criteria?

- Direct access a page and verify that an empty cart is not created anymore

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
It's important to remember the carts that were already created and need to be retrieve when the user enter the store. @zfmaster

**Comment by zfmaster** [comment]
Implemented in https://github.com/vuestorefront/magento2/pull/182
