### ISSUE TITLE
[Bug]: Cannot query field "swatch_data" on type "ConfigurableProductOptionsValues"

### ISSUE THREAD

**Issue by jonathanribas** [vuestorefront/magento2#150]
### Expected Behavior

I should be able to see categories in header navigation menu and browse category / product pages.

### Actual Behavior

When I launch build I can see the following error several times as output:
`ERROR  [VSF][error]:  [GraphQL error]: Message: Cannot query field "swatch_data" on type "ConfigurableProductOptionsValues"., Location: [column: 7, line: 94], Path: undefined`

I can't:
- see categories on header navigation menu
- access a category
- access a product page
- search for a product

### Steps to reproduce

Run `yarn && yarn dev` and check output:
` ERROR  [VSF][error]:  [GraphQL error]: Message: Cannot query field "swatch_data" on type "ConfigurableProductOptionsValues"., Location: [column: 7, line: 94], Path: undefined                                                                  15:37:45`

### What version of Magento 2 integration are you using?

Adobe Commerce 2.4.3

### What version of Node.js are you using?

v14.17.5

### What browser (and version) are you using?

Chrome 92.0.4515.159 (Official Build) (x86_64)

### What operating system (and version) are you using?

Mac OSX

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zfmaster** [comment]
Hi @jonathanribas ! Which integration version do you use? Is it `v1.0.0-beta.2` or you are on `develop` branch? In other words - how did you installed the project?

**Comment by jonathanribas** [comment]
@zfmaster I am on `develop` branch, I've just tried `v1.0.0-beta.2` and it doesn't work too.
I've launched project with:
`vsf init <project_name> && cd <project_name> && yarn && yarn dev`

**Comment by jonathanribas** [comment]
It's not a bug, sorry! 

Just don't forget to enable the following M2 modules:
- `Magento_SwatchesGraphQl`
- `Magento_SwatchesLayeredNavigation`

_PS: We had them disabled (replaced on `composer.json`) for performance optimization on our current live project on M2 monolith._
