### ISSUE TITLE
[Bug]: Complete loading during navigation

### ISSUE THREAD

**Issue by jonathanribas** [vuestorefront/magento2#151]
### Expected Behavior

In guest mode, when I browse from homepage to PLP and PDP, we should have a smooth transition without a complete loading page.

It should only load missing components from the new page we are accessing.

### Actual Behavior

In guest mode, when I browse from homepage to PLP and PDP, I can see a blank page and a full loading page, assets load again.

It seems we don't have smooth PWA effect loading only missing components from the new page we are accessing.

### Steps to reproduce

- Browse website in guest mode
- You will see a blank page between the pages you browse

### What version of Magento 2 integration are you using?

Adobe Commerce 2.4.3 / VSF 1.0.0-rc.2

### What version of Node.js are you using?

v14.17.5

### What browser (and version) are you using?

Chrome 92.0.4515.159 (Official Build) (x86_64)

### What operating system (and version) are you using?

Mac OSX

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
We need to replicate the CT demo effect.

**Comment by bloodf** [comment]
Fixed on #180
