### ISSUE TITLE
[Bug]: Increase / decrease product quantity from micro cart failed

### ISSUE THREAD

**Issue by jonathanribas** [vuestorefront/magento2#153]
### Expected Behavior

I should be able to increase or decrease product quantity from micro cart.

### Actual Behavior

I can't increase or decrease product quantity from micro cart.

`{"graphQLErrors":[{"message":"The cart isn't active.","extensions":{"category":"graphql-no-such-entity"},"locations":[{"line":266,"column":3}],"path":["updateCartItems"]}],"networkError":null,"message":"GraphQL error: The cart isn't active."}`

### Steps to reproduce

- Add a product to you cart
- Open micro cart
- Click + to increase or - to decrease quantity

### What version of Magento 2 integration are you using?

Adobe Commerce 2.4.3 / VSF 1.0.0-rc.2

### What version of Node.js are you using?

v14.17.5

### What browser (and version) are you using?

Chrome 92.0.4515.159 (Official Build) (x86_64)

### What operating system (and version) are you using?

Mac OSX

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
I tried to reproduce this bug, and for me it was normal. Can you please give me more detailed instructions, on what type of product, or a complete step-by-step under a magento sample data API so I can reproduce?

**Comment by zfmaster** [comment]
@bloodf we found with @jonathanribas approximate flow how it could happen and solution to prevent is also ready so I reassign this bug to me and will prepare fix soon.

**Comment by zfmaster** [comment]
Fixed in https://github.com/vuestorefront/magento2/pull/182
