### ISSUE TITLE
[Bug]: Clicking on product image thumbnails don't update main product image

### ISSUE THREAD

**Issue by jonathanribas** [vuestorefront/magento2#155]
### Expected Behavior

If I click on a product image thumbnail on product page, it should change the main image display on screen.

### Actual Behavior

Nothing happen if I click on a product image thumbnail on product page.

For information, on direct access to a product page, if I click on a product image thumbnail, it switches it to the main image correctly.

### Steps to reproduce

- Browse home page
- Click on a product inside `New Products` block
- Click on a product image thumbnail
- Nothing happens

### What version of Magento 2 integration are you using?

Adobe Commerce 2.4.3 / VSF 1.0.0-rc.2

### What version of Node.js are you using?

v14.17.5

### What browser (and version) are you using?

Chrome 92.0.4515.159 (Official Build) (x86_64)

### What operating system (and version) are you using?

Mac OSX

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
I think this is related to SFUI, will talk to the SFUI team to see :) because it's all fine in our side :)
