### ISSUE TITLE
[Bug]: Forgotten password link is broken

### ISSUE THREAD

**Issue by jonathanribas** [vuestorefront/magento2#157]
### Expected Behavior

When I click on Forgotten password link, I should be able to reset my password if I have an account.

### Actual Behavior

When I click on Forgotten password link, nothing happens.

### Steps to reproduce

- Click on My Account icon
- Click on Forgotten Password link
- Nothing happens

### What version of Magento 2 integration are you using?

Adobe Commerce 2.4.3 / VSF 1.0.0-rc.2

### What version of Node.js are you using?

v14.17.5

### What browser (and version) are you using?

Chrome 92.0.4515.159 (Official Build) (x86_64)

### What operating system (and version) are you using?

Mac OSX

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
The `useUserForgotPassword` composable was added on the latest version of Vue Storefront only. Need to implement it :)

**Comment by bloodf** [comment]
Need more settings on Magento side for URL to redirect, but has the alias that Magento uses

Fixed on PR #170
