### ISSUE TITLE
[Bug]: Update newsletter subscription preference doesn't work

### ISSUE THREAD

**Issue by jonathanribas** [vuestorefront/magento2#159]
### Expected Behavior

Update my newsletter subscription should work.

### Actual Behavior

I can't update my newsletter subscription option:

It's actually calling `/api/magento/updateCustomerEmail` endpoint posting `[{}] 0: {}`

`{"graphQLErrors":[{"message":"Variable \"$email\" of required type \"String!\" was not provided.\n\nVariable \"$password\" of required type \"String!\" was not provided.","extensions":{"category":"graphql"}}],"networkError":null,"message":"GraphQL error: Variable \"$email\" of required type \"String!\" was not provided.\n\nVariable \"$password\" of required type \"String!\" was not provided."}`

### Steps to reproduce

- Login to your account
- Go to your Account / Newsletter
- Update you preference
- You have an error in your Dev Tools console

### What version of Magento 2 integration are you using?

Adobe Commerce 2.4.3 / VSF 1.0.0-rc.2

### What version of Node.js are you using?

v14.17.5

### What browser (and version) are you using?

Chrome 92.0.4515.159 (Official Build) (x86_64)

### What operating system (and version) are you using?

Mac OSX

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
Fixed on PR #170
