### ISSUE TITLE
[Bug]: No notification on password change

### ISSUE THREAD

**Issue by jonathanribas** [vuestorefront/magento2#160]
### Expected Behavior

When you change your password, you should see a notification.

### Actual Behavior

When you change your password, you can't see any notification on screen.

### Steps to reproduce

- Login to your account
- Access My Account / Change password
- Change your password
- You won't see any notification if it has success or fail

### What version of Magento 2 integration are you using?

Adobe Commerce 2.4.3 / VSF 1.0.0-rc.2

### What version of Node.js are you using?

v14.17.5

### What browser (and version) are you using?

Chrome 92.0.4515.159 (Official Build) (x86_64)

### What operating system (and version) are you using?

Mac OSX

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
Fixed on PR #170
