### ISSUE TITLE
[Bug]: duplicate content on product page

### ISSUE THREAD

**Issue by jonathanribas** [vuestorefront/magento2#163]
### Expected Behavior

If you access a fake product URL, you should have a 404 content page with HTTP code 404.

You should only be able to access a product page through a single link in order to avoid duplicate content: the one informed on URL key on M2 product page edition.

### Actual Behavior

If you access a fake product URL for a known Product ID, you have a product page with a 200 HTTP Code. This leads to duplicate content.

### Possible Solution

- Show a 404 CMS page
- Send a 404 HTTP Code to browser = SEO Best Practice for not found pages

### Steps to reproduce

- Access a product page
- Change URI (.html part after `/p/(:num)/(:url_key).html`
- You will have the product page

### What version of Magento 2 integration are you using?

Adobe Commerce 2.4.3 / VSF 1.0.0-rc.2

### What version of Node.js are you using?

v14.17.5

### What browser (and version) are you using?

Chrome 92.0.4515.159 (Official Build) (x86_64)

### What operating system (and version) are you using?

Mac OSX

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
fixed on #180
