### ISSUE TITLE
[Bug]: Add a product to my cart from wishlist is not working

### ISSUE THREAD

**Issue by jonathanribas** [vuestorefront/magento2#166]
### Expected Behavior

I should be able a product to my cart from my wishlist.

### Actual Behavior

It's not happening all the time but sometimes I can't add a product to my cart from my wishlist. It creates an infinite loop call.

### Possible Solution

If `cartId` is not present on add to cart request from wishlist, it should throw an error and don't create a loop.
 
### Steps to reproduce

- Login to your account
- Add a product to your wishlist
- Go to My Wishlist inside My Account
- Add the product to your cart
- It will creates a infinite loop calling M2 endpoint

### What version of Magento 2 integration are you using?

Adobe Commerce 2.4.3 / VSF 1.0.0-rc.2

### What version of Node.js are you using?

v14.17.5

### What browser (and version) are you using?

Chrome 92.0.4515.159 (Official Build) (x86_64)

### What operating system (and version) are you using?

Mac OSX

### Relevant log output
Error posting to `/api/magento/addProductsToCart`

`message: "GraphQL error: Variable \"$cartId\" of required type \"String!\" was not provided."`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zfmaster** [comment]
@jonathanribas I need help with reproducing this bug. 
For whishlist is used same addItem as for all other places, so in case we still have a bug we should it could be a serious one. 
Could you provide more data about product was used, etc?

**Comment by zfmaster** [comment]
Was able to reproduce. As expected, problem wasn't in wishlist, but in add to cart in general. 
Steps to reproduce:
1. Log in with customer and add products to basket
2. Duplicate tab
3. In one tab proceed to checkout and complete order
4. In second tab try to add product to basket
5. Observe infinite loop.

It's possible to reproduce bug without second tab but more complicated.

**Comment by zfmaster** [comment]
Fixed in https://github.com/vuestorefront/magento2/pull/172
