### ISSUE TITLE
[Bug]: [Related Products] The name value of related products is NULL

### ISSUE THREAD

**Issue by jdperez128** [vuestorefront/magento2#179]
### Expected Behavior

Adding to product anything related products, in the product view, show the carousel of related products.

if I assign related products to one product, if I execute the query in the GraphQl IDE of Chrome I see that the result is correct:
<img width="911" alt="queryGraphql" src="https://user-images.githubusercontent.com/11404725/135074939-f560f1ec-529f-44f4-a509-0c08d771f178.png">

but.. when I go to see the carousel in the product, the product don't show my related products.

I see this:
`var getProductRelatedProduct = function (product) { var _a; return ((_a = product === null || product === void 0 ? void 0 : product.related_products) === null || _a === void 0 ? void 0 : _a.filter(function (p) { return p.name && p.uid; })) || []; };`

when I see it, go to review the component and see that the related products have the name value to NULL, then it don't be return of product.
![vueConsult](https://user-images.githubusercontent.com/11404725/135075014-13e77adb-a33b-4b15-8899-7bc4ac23d0e0.png)

Reviewing this demo: https://m2-vsf.caravelx.com/ , see that have the same problem:
![vueDemoTest](https://user-images.githubusercontent.com/11404725/135075049-fdfac259-077f-4dd5-aef4-c3f9cb9beb1e.png)

### Actual Behavior

VSF don't show carousel related products.

### Possible Solution

I don't know.. Review the productData of VSF.

### Steps to reproduce

Magento2 Admin:

1. Catalog -> Product
2. Click  in "Edit" of anything product
3. We go to [Related Products, Up-Sells, and Cross-Sells] Add related products

Terminal, execute:

1. `php bin/magento indexer:reindex`
2. `php bin/magento cache:flush`

VSF:

1. `yarn dev`
2. Go to the selected product in the M2Admin

### What version of Magento 2 integration are you using?

2.4.2-p2

### What version of Node.js are you using?

14.17.5

### What browser (and version) are you using?

Chrome 94.0.4606.61

### What operating system (and version) are you using?

macOs Big Sur

### Relevant log output

```shell
Don't have log output.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
@jdperez128 fixed on the `develop` branch :)

**Comment by jdperez128** [comment]
Perfect, thanks @bloodf !
