### ISSUE TITLE
[Feature]: Url rewrites

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#181]
### How the project can be improved?
Need to use Magento url rewrites for categories and products.
In product object we get this "url_rewrites":[{"url":"$$$$","__typename":"UrlRewrite"}]

### What are the acceptance criteria?
* [ ] categories url rewrites
* [ ] products url rewrites

### Code of Conduct
* [x] I agree to follow this project's Code of Conduct

**Comment by sequensucks** [comment]
Can u take this issue to the next sprint? Its necessary feature, because people can't to start a new site without SEO.

**Comment by Frodigo** [comment]
OK, category and product pages have SEO-friendly URLs without prefixes.

Tested with the following browsers:

Desktop: Chrome 104, Safari 15.6, Firefox 103.

Mobile: Google Chrome 104, Safari 15.5, Firefox 103, Samsung Internet Browser 17.
