### ISSUE TITLE
[Bug]: [Account] [Addresses Details] UserAddressDetails Component does not actualize

### ISSUE THREAD

**Issue by jdperez128** [vuestorefront/magento2#184]
### Expected Behavior

When I am in the Addresses Details and delete one address, show list of addresses without the address deleted.

### Actual Behavior

When I am in the Addresses Details and delete one address, the address is deleted, but the component not is updated. Then if I do click again it show next message:
![Captura de pantalla 2021-10-01 a las 16 29 04](https://user-images.githubusercontent.com/11404725/135638413-97442ef5-b39e-4e55-a0c7-af95912d025c.png)

this message, I believe that the address is deleted into Magento show one error 500 because not find the address.

### Possible Solution

In to `removeAddress` method of AddressesDetails.vue Component, add in the end `await load();`.

### Steps to reproduce

-> VSF:

1. Do login with one account.
2. Go to My Account -> Addresses Details.
3. Have 2 addresses.
4. Delete the not default address.

### What version of Magento 2 integration are you using?

2.4.2-p2

### What version of Node.js are you using?

14.17.5

### What browser (and version) are you using?

Chrome 94.0.4606.61

### What operating system (and version) are you using?

macOs Big Sur

### Relevant log output

```shell
Nothing.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zfmaster** [comment]
Fixed in https://github.com/vuestorefront/magento2/pull/189

**Comment by jdperez128** [comment]
Thanks! @zfmaster :)
