### ISSUE TITLE
[Feature]: headers in requests

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#194]
### How the project can be improved?

Need to implement headers in requests. Can be as 1 more param in queries and mutations.
https://devdocs.magento.com/guides/v2.4/graphql/send-request.html#headers

### What are the acceptance criteria?

- [x] add headers in requests

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
added to [Roadmap 1.0.0](https://github.com/vuestorefront/magento2/projects/5)
