### ISSUE TITLE
[Bug]: [Checkout] Shipping/Billing Address lose the region option

### ISSUE THREAD

**Issue by jdperez128** [vuestorefront/magento2#197]
### Expected Behavior
When I write my first address in the Shipping Section or "Add New Address", I selected one region and when you click in "Select Shipping Method", I expected see the region selected.

### Actual Behavior
When I write my first address in the Shipping Section or "Add New Address", I selected one region and when you click in "Select Shipping Method", the region selected is empty.

The curious is that, I received one error about this, but.. if I finish the order, I have correctly the region.

### Steps to reproduce
-> VSF:

1. Add one product to cart
1. Go to Checkout
1. In the Shipping Section, write one addresses
1. Click in "Select Shipping Method"
1. Review the State/Province

### What version of Magento 2 integration are you using?
2.4.2-p2

### What version of Node.js are you using?
14.17.5

### What browser (and version) are you using?
Chrome 94.0.4606.61

### What operating system (and version) are you using?
macOs Big Sur

### Relevant log output
```shell
VSF

[VSF][error]:  [GraphQL error]: Message: Region is required., Location: [column: 3, line: 2], Path: setBillingAddressOnCart


Magento

main.ERROR: Region is required. {"exception":"[object] (GraphQL\\Error\\Error(code:0): Region is required. at /Users/jdperez/Sites/optimo/magento/vendor/webonyx/graphql-php/src/Error/Error.php:174, Magento\\Framework\\GraphQl\\Exception\\GraphQlInputException(code: 0): Region is required. at vendor/magento/module-quote-graph-ql/Model/Cart/QuoteAddressFactory.php:127)"} []
```

### Code of Conduct
* [x] I agree to follow this project's Code of Conduct

┆Attachments: <a href="https://vsf.atlassian.net/rest/api/2/attachment/content/11100">Sizzy- localhost3000 26Jan 15.20.mp4</a>

**Comment by bloodf** [comment]
added to [Roadmap 1.0.0](https://github.com/vuestorefront/magento2/projects/5)
