### ISSUE TITLE
[Bug]: expired user token

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#198]
### Expected Behavior
Question/expected result.
What to do when user token is expired but page was not reload?

### Actual Behavior
when u stay a long in account and try to change address u r getting error in methods save, update

request to api/magento/createCustomerAddress
getting an error in console
useAddresses/save TypeError: Cannot read properties of undefined (reading 'createCustomerAddress')

const {
remove,
update,
save,
error: errorAddresses
} = useAddresses();
and in error 

![width=200,height=183](https://user-images.githubusercontent.com/89065178/136443228-cf4c2983-c655-41df-8e30-0cf1dbb3a4b6.png)

### Possible Solution
1. Handle token expiration
1. Redirect to the homepage
1. Display a notification about logging out because of inactivity
1. Remove the "Remember me" checkbox from the login popup
1. Update the docs and stand out that we use default Magento process

### Steps to reproduce
1. Log in. to customer account
1. got to my account
1. go to address details
1. click: change address
1. Wait for session expired, or remove vsf-customer cookie
1. Submit form
1. Observe the error

### What version of Magento 2 integration are you using?
2.4.3

### What version of Node.js are you using?
v14.17.5

### What browser (and version) are you using?
Chrome Version 94.0.4606.71 (Official Build) (x86_64)

### What operating system (and version) are you using?
macOS Version 11.6 (20G165)

### Code of Conduct
* \[x] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
added to [Roadmap 1.0.0](https://github.com/vuestorefront/magento2/projects/5)
