### ISSUE TITLE
Add Filters (aggregations) to the Category.vue page

### ISSUE THREAD

**Issue by bloodf** [vuestorefront/magento2#20]
In the `Category.vue` page the `filters` sidebar is not working, due to the integration with the Magento `aggregations`.

It needs to be added.

**Comment by hcmlopes** [comment]
I am currently working on this feature

**Comment by hcmlopes** [comment]
Update:
Currently showing the filters and ability to apply certain filters are working. 

In the coming week I am looking to get price filter to work as expected and also address some strange UI behavior that doesn't show which filter is currently applied.

If nothing else comes up during the process this will be ready to go
