### ISSUE TITLE
[Feature]: CPF, CPNJ, Neighborhood, Complement in Payment Brazil

### ISSUE THREAD

**Issue by kadukr** [vuestorefront/magento2#206]
### How the project can be improved?

Hi,

We are nationalizing the platform for Brazil, and we want to use the magento taxvat... we didn't find any getters in vuestorefront and composables.

We also need to capture street 3 and 4 from magento
in the array it comes as street[2] and street[3]

Do you have any plans for the entry of these items in the next sprints? 

### What are the acceptance criteria?

- [ Taxvat, street[3], street[2] do magento em vuestorefront ]

### Additional information

congratulations thank you gratitude

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
@kadukr I've added on the development brach new field called `neighborhood` and `extra`, also the address returns the `vat_id` and the composables now handles the `tax_vat`.

To implement on your store, it's just a matter of developing the interface on the theme.
