### ISSUE TITLE
[Bug]: Warning on build

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#215]
### Actual Behavior

(node:65977) [DEP0128] DeprecationWarning: Invalid 'main' field in '.../node_modules/@vue-storefront/nuxt-theme/package.json' of 'lib/module.js'. Please either fix that or report it to the module author

### What version of Magento 2 integration are you using?

2.4.3

### What version of Node.js are you using?

v14.17.5

### What browser (and version) are you using?

Chrome Version 94.0.4606.71 (Official Build) (x86_64)

### What operating system (and version) are you using?

macOS Version 11.6 (20G165)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdanilowicz** [comment]
Same here:

`(node:4066) [DEP0128] DeprecationWarning: Invalid 'main' field in '<bla_bla_bla>/node_modules/@vue-storefront/nuxt-theme/package.json' of 'lib/module.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)`

**Comment by bloodf** [comment]
Fixed

**Comment by vishal67commerce** [comment]
@bloodf Can you Please share the fixed code or any commit link ?
