### ISSUE TITLE
[Bug]: Pagination for customer orders

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#218]
### How the project can be improved?

Add in orderGetters a method getPagination like in wishlistGetters.getPagination or facetGetters.getPagination.

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
I've created the base under the API, but seems that the Magento GraphQL is not working properly, as the parameters is not being respected and not returning properly.

**Comment by sequensucks** [comment]
Thanks a lot! We will check it in our magento and try to fix.

**Comment by bloodf** [comment]
@sequensucks fixed on development branch
