### ISSUE TITLE
[Bug]: Pagination for wishlist

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#219]
### Actual Behavior

Pagination for wishlist doesn't work.
I can't change a currentPage and pageSIze...
I checked the demo and it doesn't work.

### What version of Magento 2 integration are you using?

2.4.3

### What version of Node.js are you using?

v16.12.0

### What browser (and version) are you using?

Chrome Version 95.0.4638.54 (Official Build) (x86_64)

### What operating system (and version) are you using?

macOS Version 11.6 (20G165)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
I've created the base under the API, but seems that the Magento GraphQL is not working properly, as the parameters is not being respected and not returning properly.

**Comment by sequensucks** [comment]
Thanks a lot! We will check it in our magento and try to fix.
