### ISSUE TITLE
ConfigurableProduct product Product.vue correct rendering with options

### ISSUE THREAD

**Issue by bloodf** [vuestorefront/magento2#22]
It needs to implement the ConfigurableProduct correct rendering with options in the `Product.vue` page

**Comment by simonmaass** [comment]
just a little note: we have products with about 40-60k variants and the product page in vsf1 was due to loading all variante a nightmare... maybe there is a chance to keep this in mind.. having a lot of variants on some products...

**Comment by bloodf** [comment]
@simonmaass can you provide a usage case of this product, working with e-commerce for a long time I never saw any product with that many variations.

**Comment by simonmaass** [comment]
yeah sure... https://www.meevo.de/medi-elegance-schenkelstruempfe

this for example is a compression sock (medical supply)... this product has 6 variable attributes with each about 5-15 values...
