### ISSUE TITLE
[Bug]: Update billingAddress

### ISSUE THREAD

**Issue by DaiLoc5698** [vuestorefront/magento2#220]
### Actual Behavior

We shouldn't update shippingMenthod when update billingAddress
When cart has only the downloadableProduct, we don't need to shippingAddress and shippingMethod, so update shippingMethod when update billingAddress will be a bug 

`magento2/packages/composables/src/composables/useBilling/index.ts `

```
save: async (context: Context, params) => {
    Logger.debug('[Magento] setBillingAddress');
    const { id } = context.cart.cart.value;

    const {
      apartment,
      sameAsShipping,
      ...address
    } = params.billingDetails;

    const setBillingAddressOnCartInput: SetBillingAddressOnCartInput = {
      cart_id: id,
      billing_address: {
        address: {
          ...address,
          street: [address.street, apartment],
        },
        same_as_shipping: sameAsShipping,
      },
    };

    const { data } = await context.$magento.api.setBillingAddressOnCart(setBillingAddressOnCartInput);

    Logger.debug('[Result]:', { data });

    /**
     * This is a workaround needed due to Magento GraphQL API
     * cleaning the Shipping method after defining the billing address
     */
    const shippingMethod = context.useShippingProvider.state.value;

    Logger.debug('[Magento]: Defining the shipping method as:', JSON.stringify(shippingMethod, null, 2));

    await context.useShippingProvider.save({
      shippingMethod: {
        carrier_code: shippingMethod.carrier_code,
        method_code: shippingMethod.method_code,
      },
    });
    /**
     * End of GraphQL Workaround
     */

    return data.setBillingAddressOnCart.cart.billing_address;
  },
```

### What version of Magento 2 integration are you using?

2.4.3

### What version of Node.js are you using?

14.17.0

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by agnezi** [comment]
Hi guys, I cant assign myself to this issue, so I'm sending here the link with my draft pull request.

https://github.com/vuestorefront/magento2/pull/225
