### ISSUE TITLE
[Bug]: Error with vue-demi dependency

### ISSUE THREAD

**Issue by jdperez128** [vuestorefront/magento2#221]
### Expected Behavior

In the `packages/theme/package.json`, we can see that the project have one dependency with `vue-demi`. I expected when run `yarn dev` can run the VSF.

### Actual Behavior

The 27/10 `vue-demi` was be updated to the 0.12.0 version (latest version). With this version, when you run `yarn dev`, VSF has the following error:
<img width="692" alt="vue-demi-error" src="https://user-images.githubusercontent.com/11404725/139284448-3cd72dec-2681-4e24-9b4c-eb3c50881365.png">

thanks!.

### Possible Solution

Change `vue-demi` to `0.11.4` version or review dependencies.

### Steps to reproduce

In the terminal run:

-> vsf init
-> cd `project-name`
-> yarn install
-> yarn dev

### What version of Magento 2 integration are you using?

2.4.2-p2

### What version of Node.js are you using?

14.17.5

### What browser (and version) are you using?

Chrome 94.0.4606.61

### What operating system (and version) are you using?

macOs Big Sur

### Relevant log output

```shell
ERROR in ./node_modules/vue-demi/lib/index.mjs
Module not found: Error: Can't resolve '@vue/composition-api/dist/vue-composition-api.mjs' in './node_modules/vue-demi/lib'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
fixed :)

**Comment by jdperez128** [comment]
I'm still having the same problem @bloodf :(
