### ISSUE TITLE
[Bug]: Add To Cart disabled for products with attributes

### ISSUE THREAD

**Issue by igorwojciechowski** [vuestorefront/magento2#228]
### Expected Behavior

After selecting attributes like size and color, customer should be able to select quantity of the product and add product to cart.

### Actual Behavior

Both quantity input and Add To Cart button are disabled

### Steps to reproduce

1. Go to Category page
2. Navigate to Product page of a product with attributes, e.g. with color and size
3. Select color and size values

### What version of Node.js are you using?

14.18.1

### What browser (and version) are you using?

Chromium Version 92.0.4504.0

### What operating system (and version) are you using?

WSL (Ubuntu 18.04)

### Screenshots

![screenshot-localhost_3000-2021 11 09-14_01_13](https://user-images.githubusercontent.com/26794636/140928956-89bef181-6385-426a-b422-42fa28ded605.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
fixed on #240
