### ISSUE TITLE
[Bug]: Heart icon not toggling on add to/remove from wishlist

### ISSUE THREAD

**Issue by igorwojciechowski** [vuestorefront/magento2#229]
### Expected Behavior

- Heart icon should switch to filled icon on add to wishlist
- Heart icon should switch to empty icon on remove from wishlist

### Actual Behavior

Heart icon does not change on either add to- and remove from wishlist

### Steps to reproduce

1. Login/Register as a customer
2. Go to Category page
3. Hover over product card
4. Click heart icon on product card to add product to wishlist

### What version of Magento 2 integration are you using?

1.0.0-rc.4.3

### What version of Node.js are you using?

14.18.1

### What browser (and version) are you using?

Chromium Version 92.0.4504.0

### What operating system (and version) are you using?

WSL (Ubuntu 18.04)

### Screenshots

![heart_icon_toggle](https://user-images.githubusercontent.com/26794636/140930266-ebc503a6-c424-4bed-8cf0-a643b6b7047c.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
fixed on #240
