### ISSUE TITLE
[Bug]: Filtering products by color or size shows no results

### ISSUE THREAD

**Issue by igorwojciechowski** [vuestorefront/magento2#230]
### Expected Behavior

Products filtered by color and/or size should be displayed on Category page when proper filters are selected

### Actual Behavior

No results are shown on Category page when color/size filters are selected

### Steps to reproduce

1. Go to Category page
2. Open Filters sidebar
3. Select size and/or color filter

### What version of Magento 2 integration are you using?

1.0.0-rc.4.3

### What version of Node.js are you using?

14.18.1

### What browser (and version) are you using?

Chromium Version 92.0.4504.0

### What operating system (and version) are you using?

WSL (Ubuntu 18.04)

### Screenshots

![filter_category](https://user-images.githubusercontent.com/26794636/140931371-4394fc82-0ddd-48ed-9b4e-46d1dd343c53.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
fixed on #240
