### ISSUE TITLE
[Bug]: Change password - success toast on invalid credentials error

### ISSUE THREAD

**Issue by igorwojciechowski** [vuestorefront/magento2#231]
### Expected Behavior

An error toast with error message should be displayed when customer changes password with incorrect data

### Actual Behavior

A success toast is being displayed even though credentials sent in password update request are not valid

### Steps to reproduce

1. Register or log in as a customer
2. Go to My Account > My Profile
3. Switch to Password Change tab
4. Insert invalid account password into Current Password input
5. Fill new and confirm passwords with valid values
6. Submit form

### What version of Magento 2 integration are you using?

1.0.0-rc.4.3

### What version of Node.js are you using?

14.18.1

### What browser (and version) are you using?

Chromium Version 92.0.4504.0

### What operating system (and version) are you using?

WSL (Ubuntu 18.04)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
fixed on #240
