### ISSUE TITLE
[Bug]: Category - products not displayed on first category page entry

### ISSUE THREAD

**Issue by igorwojciechowski** [vuestorefront/magento2#236]
### Expected Behavior

Products should be displayed on category page as soon as product data is fetched from the backend.

### Actual Behavior

Product data is fetched but not displayed on the first entry on category page. Displaying products on category page requires page reloading.

### Steps to reproduce

1. Go to home page
2. Navigate to category page, e.g. click "Women" on the header
3. Wait until loader on category page disappears
4. Repeat steps 1-2

### What version of Magento 2 integration are you using?

1.0.0-rc.4.3

### What version of Node.js are you using?

14.18.1

### What browser (and version) are you using?

Chromium Version 92.0.4504.0

### What operating system (and version) are you using?

WSL (Ubuntu 18.04)

### Screenshots

![empty_category](https://user-images.githubusercontent.com/26794636/141454627-c36e6ada-720b-47ab-9cb1-e6b04a79f277.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
fixed on #240
