### ISSUE TITLE
[Bug]: Category - clicking add to cart button on products with attributes redirects to PDP

### ISSUE THREAD

**Issue by igorwojciechowski** [vuestorefront/magento2#237]
### Expected Behavior

Clicking add to cart button should add product to cart

### Actual Behavior

If given product has color/size attributes, clicking add to cart button on product card on category page redirects to product's PDP

### Steps to reproduce

1. Go to category page
2. Hover over product with color and/or size attributes
3. Click add to cart icon/button

### What version of Magento 2 integration are you using?

1.0.0-rc.4.3

### What version of Node.js are you using?

14.18.1

### What browser (and version) are you using?

Chromium Version 92.0.4504.0

### What operating system (and version) are you using?

WSL (Ubuntu 18.04)

### Screenshots

![category_add_to_cart](https://user-images.githubusercontent.com/26794636/141459628-c79279ce-c8d8-4557-9852-9ba2a70e70ad.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by simonmaass** [comment]
well you have to chose a configuration first... not sure what you expected?

**Comment by bloodf** [comment]
@igorwojciechowski until we have a front selector of the current option, I don't see other solution for this :/
