### ISSUE TITLE
[Bug]: Password validation does not match backend validation

### ISSUE THREAD

**Issue by igorwojciechowski** [vuestorefront/magento2#238]
### Expected Behavior

Magento password should have at least (minimum) 3 of 4 existing classes: Lower Case, Upper Case, Digits, Special Characters.

### Actual Behavior

Password must have all 4 of existing classes: Lower Case, Upper Case, Digits, Special Characters.
Error message: "The password must contain at least: 1 uppercase letter, 1 lowercase letter, 1 number, and one special character (E.g. , . _ & ? etc)"

### Steps to reproduce

1. Go to home page as a guest user
2. Click account icon to open login/registration modal
3. Switch to registration modal if not already displayed
4. Insert "aaaaaaaa" into password input

### What version of Magento 2 integration are you using?

1.0.0-rc.4.3

### What version of Node.js are you using?

14.18.1

### What browser (and version) are you using?

Chromium Version 92.0.4504.0

### What operating system (and version) are you using?

WSL (Ubuntu 18.04)

### Screenshots

![image](https://user-images.githubusercontent.com/26794636/141465438-79b350f9-64c1-4b74-8dd8-dbfb22b1be96.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
fixed on #240
