### ISSUE TITLE
[Bug]: Category - TypeError on pagination exceeding pages limit

### ISSUE THREAD

**Issue by igorwojciechowski** [vuestorefront/magento2#239]
### Expected Behavior

Category page with empty results should be displayed; error should be handled

### Actual Behavior

TypeError is being raised

### Steps to reproduce

1. Go to category page
2. Add `page` parameter to url with a value exceeding pages limit, e.g. if API fetches 10 pages of products, set `page` to 11.
```
http://localhost:3000/c/gear.html?page=1337
```
3. Reload page with changed `page` parameter

### What version of Magento 2 integration are you using?

1.0.0-rc.4.3

### What version of Node.js are you using?

14.18.1

### What browser (and version) are you using?

Chromium Version 92.0.4504.0

### What operating system (and version) are you using?

WSL (Ubuntu 18.04)

### Relevant log output

```shell
TypeError
Cannot read property 'filter' of undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
fixed on #240
