### ISSUE TITLE
[Feature]: override default GraphQL queries

### ISSUE THREAD

**Issue by marc-arnoult** [vuestorefront/magento2#245]
### How the project can be improved?

Right now, to override the current behavior of the GraphQL queries we need to use `customQuery` composable.

However we have to repeat that pattern everywhere if it's not used for 1 given call, it involves to replace all the composable call and to send the GraphQL body over the network. It might be interesting to replace the default graphQL query from the middleware configuration.

Second problem, if we need for example to remove a field from the customer query we need to override several method from the `useUser` composable to just change one row. 
A lot of work and it would be even more difficult to upgrade the theme in the future.

Example use case : 

We have to remove the field `allow_remote_shopping_assistance` to prevent an error from the graphQL endpoint from the customer query ( we do not use this magento2 feature )

In order to do that we have to use a custom composable with all the user logic ( login, registration... )

We have to add the custom query with the default query key to override it, it would not change de current behavior with custom queries.

Example : 
```
integrations: {
    magento: {
      customQueries: {
       // current behavior
        customCustomer: () => {
          ...
        },
        // Will override the default behavior everywhere
        customer: () => {
          ...
        }
      },
  }
}
```

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marc-arnoult** [comment]
@bloodf it is ok for you if i start working on this enhancement ?

**Comment by sequensucks** [comment]
yes. I need it too!
Because at now i have replaced an useCart and an useWishlist=(

**Comment by marc-arnoult** [comment]
FI i'm currently working on this one.

**Comment by Frodigo** [comment]
Hi @marc-arnoult, thanks for your update.

**Comment by Frodigo** [comment]
This is done.
