### ISSUE TITLE
Where is the documentation of the integration in middleware.config.js?

### ISSUE THREAD

**Issue by zerbfra** [vuestorefront/magento2#246]
### Provide a description of requested docs changes

Hi, I'm trying to configure my Magento 2 install...I have multi store enabled with multiple stores.

From `middleware.config.js` I found out this:

```
        websites: {
          base: {
            code: 'base',
            defaultStoreGroup: 'main_website_store',
            storeGroups: {
              main_website_store: {
                code: 'main_website_store',
                defaultStore: 'default',
                stores: {
                  default: { code: 'default' },
                  de: { code: 'de' },
                  fr: { code: 'fr' },
                },
              },
            },
          },
        },
   ```
   
   Where can I find documentation about the integration? In particular this section?
   Thanks
   
   

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
The feature is not finished yet, we have mockups for how we think it can be done :)

Once we have the feature ready we will have the documentation ewady

**Comment by bloodf** [comment]
The new MultiStore is automatically and handled directly in the theme storefront, it doesn't need any configuration. Already created on the development branch :)
