### ISSUE TITLE
[Bug][My account][Address book]: It's not possible to back from Address details page to Addresses page

### ISSUE THREAD

**Issue by Frodigo** [vuestorefront/magento2#256]
### Expected Behavior

When I open an address form by clicking the "Add new address" button or just edit the existing address and click the "back" browser button, I expect to go back to the Addresses page. 

### Actual Behavior

When I click the "back" browser button, storefront redirects me to another page (which is a previous one before I visited the Addresses details page.

### Possible Solution

Add address details page as a separate route, or add an entry to browser history when the address form appears.

### Steps to reproduce

1. Log in as a user
2. Go to my account
3. Go to the Addresses details page
4. Click the "Add the address" button
5. Click the browser "back" button

### What version of Magento 2 integration are you using?

1.0.0-rc.4.5

### What version of Node.js are you using?

16.13

### What browser (and version) are you using?

Chrome 95

### What operating system (and version) are you using?

macOs Montery 12.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
The issue has been fixed by @bartoszherba. Here is the corresponding pull request: https://github.com/vuestorefront/magento2/pull/258

Thanks for your help!

@bartoszherba, could you verify if your fix works correctly on our dev environment: https://demo-magento2-canary.europe-west1.gcp.storefrontcloud.io/ ? 

Thanks,
Marcin

**Comment by bartoszherba** [comment]
@Frodigo 
Tested and works as expected.

**Comment by Frodigo** [comment]
Thanks!
