### ISSUE TITLE
[Bug][Product Page]: HTML code is not supported in product description 

### ISSUE THREAD

**Issue by Frodigo** [vuestorefront/magento2#257]
### Expected Behavior

1. As a merchant, I want to use the WYSIWYG editor in the admin panel to create a product description

![Screenshot 2021-12-07 at 12 16 27](https://user-images.githubusercontent.com/11998249/145019687-e5c4f9cc-378a-41b8-8eba-9948c9b8631c.png)

2. As a storefront user I want to see a rendered product description in the browser

### Actual Behavior

HTML code is not rendered:

![Screenshot 2021-12-07 at 12 14 26](https://user-images.githubusercontent.com/11998249/145019387-25182c63-a3b8-4526-83ac-d631bd9745a0.png)

### Possible Solution

Update template to render HTML code.

### Steps to reproduce

1. Update any product on the admin panel and put HTML there, or if you are connected with our Magento Demo instance, please find the "Joust Duffle Bag" product on the storefront.
2. Take a look at the product description and notice that HTML code is not rendered.

### What version of Magento 2 integration are you using?

1.0.0-rc.4.5

### What version of Node.js are you using?

16.13

### What browser (and version) are you using?

Chrome 95

### What operating system (and version) are you using?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
Hi, @bloodf. Is this PR: https://github.com/vuestorefront/magento2/pull/264 related to this issue?

**Comment by bloodf** [comment]
Yes @Frodigo, right now Magento is sending the Encoded HTML in the API. So this is a communication problem with the API, not anymore at the theme layer lever.
