### ISSUE TITLE
[Bug]: Product with only one attribute does not work

### ISSUE THREAD

**Issue by ethinkers** [vuestorefront/magento2#263]
### Expected Behavior
Return product is check stock using canAddToCart variable in front end.

### Actual Behavior
hi, i installed sample data it works perfectly!
the products are registered with 2 attributes color, and size

when I remove one attribute my api-client gets the error...
breaking the canAddToCart variable for the purchase button in the frontend
does not return the product

look this request in xhr

![image](https://user-images.githubusercontent.com/42674431/145083776-23381725-cd9b-4e96-b18e-11515bb4d477.png)
![image](https://user-images.githubusercontent.com/42674431/145083787-e7bd0347-d9b0-48a1-b281-cc948b74bcd9.png)
![image](https://user-images.githubusercontent.com/42674431/145083947-fcc299f7-ba85-416e-81d1-917a278980f3.png)

### What version of Magento 2 integration are you using?
2.4

### What version of Node.js are you using?
15.14

### What browser (and version) are you using?
Chome

### What operating system (and version) are you using?
Mint

### Code of Conduct
* [x] I agree to follow this project's Code of Conduct

┆Attachments: <a href="https://vsf.atlassian.net/rest/api/2/attachment/content/11137">Antonia Racer Tank _ Products _ Inventory _ Catalog _ Magento Admin 2022-02-02 12-02-59.png</a>

**Comment by Frodigo** [comment]
@ethinkers, thank you for reporting this issue. We will take a look. 

Thanks, 
Marcin Kwiatkowski
