### ISSUE TITLE
Apollo In Memory cache

### ISSUE THREAD

**Issue by Frodigo** [vuestorefront/magento2#266]
### What is your question / Please describe your issue

We use apollo-cache-inmemory dependency in api-client but since @apollo/client version 3 that InMemory cache is a part of apollo/client 

Are there any concerns about removing the apollo-cache-inmemory  dependency and using it directly from the @apollo-client? 

Take a look at Apollo docs for reference: 
https://www.apollographql.com/docs/react/caching/cache-configuration/

### What version of Magento 2 Integration are you using?

1.0.0-rc.4.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
It's possible to use it, it's just how it was being imported.

**Comment by Frodigo** [comment]
I see, but there is also `IntrospectionFragmentMatcher` imported, and it's not a part of @apollo/client. 

Can you explain to me the purpose of using the `IntrospectionFragmentMatcher`?

Thanks,
Marcin
