### ISSUE TITLE
[Bug]: placeOrder must use OrderPaymentMethod interface to help support additional data required by third party payment gateway providers

### ISSUE THREAD

**Issue by ashokraman** [vuestorefront/magento2#268]
### Expected Behavior
To be able to supply additional parameters for payment gateway providers to maintain their tables in their plugins

### Actual Behavior
Currently only the payment code and title are supported in a generic way

### Possible Solution
Use the OrderPaymentMethod interface for placeOrder mutation

### Steps to reproduce
Add a payment gateway provider (Razorpay)
Select that method in vuestorefront and click on makeOrder
Responds with 'Razorpay details missing' and fails to make an entry in sales_order

### What version of Magento 2 integration are you using?
3.4.x

### What version of Node.js are you using?
14

### What browser (and version) are you using?
Chrome, Firefox

### What operating system (and version) are you using?
Windows 10

### Code of Conduct
* [x] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
Hi @ashokraman, thanks for your report. We will analyze this issue on our subsequent backlog refinement. 

Thanks,
Marcin

**Comment by ashokraman** [comment]
Payment gateways must provide custom graphgl apis to provide information specific to their gateway implementation, so my initial assessment of a generic placeOrder was incorrect and this bug can be closed. For instance razorpay supports placeRazorpayOrder as part of their plugin extension. Any thoughts on how VSF will support such graphql calls (using VSFContext?). Thanks
