### ISSUE TITLE
[Feature]: customQuery is not implemented on useFacet composable

### ISSUE THREAD

**Issue by Aliaaaam** [vuestorefront/magento2#283]
### What is your question / Please describe your issue

The feature does not seem implemented yet, it would be great to have it in the next release...

### What version of Magento 2 Integration are you using?

1.0.0-rc.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
Thanks, @Aliaaaam, for your report. We will take a look at this on the subsequent backlog refinement.

**Comment by sequensucks** [comment]
@Frodigo @Aliaaaam this task was done within this https://github.com/vuestorefront/magento2/issues/373
