### ISSUE TITLE
[Bug]: Multi store

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#311]
### Actual Behavior

I can't:
- load 3 stores with own locales
- load a special store at the first time, i'm getting always default store, because a vsf-store cookie is empty at the first time.

### What version of Magento 2 integration are you using?

2.4.3

### What version of Node.js are you using?

v16.12.0

### What browser (and version) are you using?

Chrome Version 96.0.4664.93 (Official Build) (x86_64)

### What operating system (and version) are you using?

macOS Version 12.0.1 (21A559)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
Verified on dev env. 

Work as expected, except store icon changing. Created another issue: https://github.com/vuestorefront/magento2/issues/365
