### ISSUE TITLE
[Feature]: Use GET HTTP method for queries instead of POST

### ISSUE THREAD

**Issue by Frodigo** [vuestorefront/magento2#322]
### How the project can be improved?

We can improve communication with Magento GraphQL API by use GET HTTP method for queries. 

### What are the acceptance criteria?

- [ ] GraphQL queries use GET method
- [ ] GraphQL mutations use POST method

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
@Frodigo this is already working. It needs more of a Magento Backend configuration than the frontend.

We have already how to configure this in the docs: https://docs.vuestorefront.io/magento/guide/creating-a-store.html#enabling-graphql-caching-on-magento-with-varnish

**Comment by Frodigo** [comment]
Thanks @bloodf
