### ISSUE TITLE
[Feature]: Currency Switcher

### ISSUE THREAD

**Issue by Frodigo** [vuestorefront/magento2#355]
### How the project can be improved?
Add Currency switcher

### What are the acceptance criteria?
* [ ]

### Code of Conduct
* [x] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
@Frodigo This is already implemented. The problem now lays in the @vue-storefront/nuxt-middleware package, which keeps returning the currency and language on the cookie value.
