### ISSUE TITLE
[Bug]: Unable to search for categories

### ISSUE THREAD

**Issue by Frodigo** [vuestorefront/magento2#359]
### Actual Behavior

Categories are not visible in search form, and there is an error in console: 

```
useCategorySearchFactory.ts?d84c:46 [VSF][error]: useCategorySearch/AppHeader:Categories/search TypeError: Cannot read properties of undefined (reading 'categoryList')
    at eval (index.ts?3944:16)
    at step (tslib.es6.js?50da:102)
    at Object.eval [as next] (tslib.es6.js?50da:83)
    at fulfilled (tslib.es6.js?50da:73)
```
![Screenshot 2021-12-17 at 12 33 42](https://user-images.githubusercontent.com/11998249/146538753-d91ecd44-984a-436d-8108-07576ade8de9.png)

### Steps to reproduce

1. Type 'Bag' in search input in header

### What version of Magento 2 integration are you using?

1.0.0-r.c-5

### What version of Node.js are you using?

16

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
It's fixed with the #266 PR
