### ISSUE TITLE
[Bug]: Override a productDetails query

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#361]
### Actual Behavior

Can't override a productDetails query.
https://docs.vuestorefront.io/magento/guide/override-queries.html

I tried like this
productDetails: ({ variables }) => ({ query: gql`${productDetailQuery}`, variables }),
and like this
productDetail: ({ variables }) => ({ query: gql`${productDetailQuery}`, variables }),

Other queries i overridden.

### What version of Magento 2 integration are you using?

2.4.3

### What version of Node.js are you using?

v16.12.0

### What browser (and version) are you using?

Chrome Version 96.0.4664.93 (Official Build) (x86_64)

### What operating system (and version) are you using?

macOS Version 12.0.1 (21A559)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
@bloodf I just wanted to ask is this PR fixes this: https://github.com/vuestorefront/magento2/pull/363 or this is another issue?

**Comment by bloodf** [comment]
The PR #363 is supposed to fix the implementation of `customQueries` @Frodigo @sequensucks

**Comment by Frodigo** [comment]
Thanks, @bloodf!

@sequensucks this will be released tomorrow with 1.0.0-r.c-5.2 version.

**Comment by sequensucks** [comment]
@Frodigo @bloodf thanks a lot!
