### ISSUE TITLE
[Bug]: TS2742

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#372]
### Actual Behavior

i'm getting errors in all composables

TS2742: The inferred type of 'useMagentoConfiguration' cannot be named without a reference to '@nuxtjs/composition-api/node_modules/@vue/composition-api'. This is likely not portable. A type annotation is necessary.

### What version of Magento 2 integration are you using?

2.4.3

### What version of Node.js are you using?

v16.12.0

### What browser (and version) are you using?

Chrome Version 95.0.4638.54 (Official Build) (x86_64)

### What operating system (and version) are you using?

macOS Version 12.0.1 (21A559)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
Are this occurring in a clean template installation? @sequensucks

**Comment by sequensucks** [comment]
1. git clone https://github.com/vuestorefront/template-magento
2. yarn install
3. open composables/useMagentoConfiguration.ts
4. you can see an error

i use a phpstorm 2021.2.3

**Comment by bloodf** [comment]
@sequensucks it's just a problem of auto inferring type, I will add a type fix for it.
