### ISSUE TITLE
[Bug]: All override queries don't work

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#373]
### Actual Behavior

https://docs.vuestorefront.io/magento/guide/override-queries.html#examples
Almost all queries worked in the rc5.1, but now they all don't work in the rc5.2

enums/customQueriesEnum.js
![image](https://user-images.githubusercontent.com/89065178/147205464-6f586c0e-e48a-42dd-9eb6-08b01d627638.png)

and use it in the middleware.config.js
![image](https://user-images.githubusercontent.com/89065178/147205539-7f32e51c-3801-4d74-9bff-539c89f026e2.png)

In the rc5.1 all queries worked expect a wishlist and a productDetail

I can't use it like this
 loadConfig({
    customQuery: {
      storeConfig: 'storeConfig'
    },
  }),

like example, i need to override a query and mutations in the useCart and i can't to pass a customQuery param.
In the rc5.1 it works.

### What version of Magento 2 integration are you using?

2.4.3

### What version of Node.js are you using?

v16.12.0

### What browser (and version) are you using?

Chrome Version 96.0.4664.93 (Official Build) (x86_64)

### What operating system (and version) are you using?

macOS Version 12.0.1 (21A559)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
@sequensucks can you try this branch and see if the problem persists?

https://github.com/vuestorefront/magento2/tree/bugfix/customQuery

I've made some changes, and tested here, but I want to make sure before releasing it :)

**Comment by sequensucks** [comment]
Cool, it's works. Tested with availableStores, storeConfig and wishlist.

**Comment by Aliaaaam** [comment]
Very urgent issue, a hotfix would be appreciated.

**Comment by bloodf** [comment]
@sequensucks @Aliaaaam PR created, I will try to release ASAP :)

**Comment by sequensucks** [comment]
@bloodf  thx a lot!
