### ISSUE TITLE
[Bug]: PDP Invalid prop: type check failed for prop "src"

### ISSUE THREAD

**Issue by bartoszherba** [vuestorefront/magento2#433]
### Expected Behavior
There are no console log errors when hovering the product's gallery.

### Actual Behavior
There are errors in console log related to images src in component when hovering over gallery images.

### Steps to reproduce
1. Go to any product page that has an image gallery
1. Hover over the main image to zoom in
1. Leave image and observe errors in console

`Invalid prop: type check failed for prop "src"`

### What version of Magento 2 integration are you using?
2.4.x

### What version of Node.js are you using?
16.13.1

### What browser (and version) are you using?
Version 96.0.4664.110 (Official Build) (arm64)

### What operating system (and version) are you using?
macOS Monterey 12.1

### Relevant log output
```shell
[Vue warn]: Invalid prop: type check failed for prop "alt". Expected String, got Undefined 

found in

---> <SfImage> at node_modules/@storefront-ui/vue/src/components/atoms/SfImage/SfImage.vue
       <SfGallery> at node_modules/@storefront-ui/vue/src/components/molecules/SfGallery/SfGallery.vue
         <Anonymous>
           <LazyHydrate>
             <ProductPage> at _theme/pages/Product.vue
               <Nuxt>
                 <DefaultLayout> at _theme/layouts/default.vue
                   <Root>
```

### Code of Conduct
* [x] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
But it's fixed in storefront-ui 0.12. Closing.
