### ISSUE TITLE
EOF Syntax Error on magento-site/graphql with caravel graphql module installed

### ISSUE THREAD

**Issue by grcatterall** [vuestorefront/magento2#442]
### What is your question / Please describe your issue

When I try accessing my 'local-domain.test'/graphql  I get an error 
`{"errors":[{"message":"Syntax Error: Unexpected <EOF>","extensions":{"category":"graphql"},"locations":[{"line":1,"column":1}]}]}`

This then also seems to be preventing the vue storefront from connecting to the site. I'm not sure what I'm supposed to see when I go to the graphql path and so I am unsure where to start debugging it.

I appreciate any help people can give (sorry for a basic question)

### What version of Magento 2 Integration are you using?

2.4.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grcatterall** [comment]
I'm a fool sorry

**Comment by cdeclerck** [comment]
Hello, 
How did you correct your problem?

**Comment by grcatterall** [comment]
Hi @cdeclerck ,

I can't fully remember but I think it was just because I wasn't passing anything to _domain.com_/graphql/

Just adding a query to the end fixed it I believe.
