### ISSUE TITLE
VuestoreFront - support VSBrdige?

### ISSUE THREAD

**Issue by nagrgkgc** [vuestorefront/magento2#457]
### What is your question / Please describe your issue
Hi VS team,

Thanks for the plugin 
#1 but question is does it support direct integration with vsbridge ES ? 
#2 graphQL is magento service and it uses magento query to find products? and not any external services like VSBRIdge to speedup everything needed render PLP, PDP?
#3 how do we escape PLP, PDP using magento query ?
#4 can we use storefront without MSI? I have not installed MSI, do we need it to work?
#5 I have installed storefront localy but I dont see customer account information on header or footer, anything should be changed here?

thank you

### What version of Magento 2 Integration are you using?
1.0.0

### Code of Conduct
* [x] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
Hi, @nagrgkgc Thanks for your questions. 

My answers are below: 

1. VSF 2 does not use an elastic search bridge anymore. 
2. Yes, we use GraphQL API to get data from Magento
3. I don't understand, could you explain? 
4. Our integration is for the Magento Community version, MSI is available in Adobe Commerce. Anyway MSI shouldn't affect storefront
5. To see customer account pages you need to log-in. There is an icon in the header that opens login/registration modal. 

Thanks,
Marcin Kwiatkowski

**Comment by nagrgkgc** [comment]
Hi @Frodigo 
#1 whats reason not using vsbridge?
#3, can we not use magento for PLP and PDP. and use vsbridge instead? vsbridge much faster compared to magento.
#4 storefront has issue with MSI , and it is throwing error if magento not installed with MSI. have you noticed this?

**Comment by Frodigo** [comment]
Hi @nagrgkgc 

1. Bridge and elastic search add some other problems and complicate architecture and development. VSF 2 architecture is based on GraphQL API. It also can be fast. 
3. I think it's possible, but custom development is needed on the api-client module. 
4. Sorry but I still don't understand. We have a demo without MSI and it works. 

Thanks,
Marcin

**Comment by nagrgkgc** [comment]
Hi @Frodigo 

thank you. please check attached which throws error as MSI not installed in my magento.
<img width="1771" alt="Screen Shot 2022-01-28 at 7 38 04 AM" src="https://user-images.githubusercontent.com/53718686/151638645-0bc3568a-51ef-4c60-84dc-b1e9c9f5df3c.png">

and I dont see any login or customer links at top. something missing here?

thanks again for the reply.

**Comment by Frodigo** [comment]
Hi @nagrgkgc, sorry for the late response. We cannot reproduce that issue. I think it's related to Magento configuration. 

Could you provide any details about your Magento instance? 

Thanks, Marcin

**Comment by nagrgkgc** [comment]
Hi @Frodigo 

I have magento2 commerce platform and i have removed all modules related to MSI. we dont use MSI feature.
install VueJs Storefront and check frontend, has issue with mentioned issue.

hope this is fine ?
