### ISSUE TITLE
[Bug]: Caching graph requests

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#476]
### Actual Behavior
when i use useGETForQueries: true in the middleware.config.js and try to change storeview i get a cached response of requests (vsf-store changed)

![width=200,height=183](https://user-images.githubusercontent.com/89065178/150862498-433d9cc6-393b-46cf-a57b-f54b3fa16223.png)

![width=200,height=183](https://user-images.githubusercontent.com/89065178/150862433-04261aca-50e7-47f1-b429-e9d73a55657e.png)

For example, a request for get categories

### Possible Solution
1. Add store code to the URL of each request
1. check if possible to purge Varnish cache when specific HTTP header is changed

### What version of Magento 2 integration are you using?
2.4.3

### What version of Node.js are you using?
v16.12.0

### What browser (and version) are you using?
Chrome Version 96.0.4664.93 (Official Build) (x86_64)

### What operating system (and version) are you using?
macOS Version 12.0.1 (21A559)

### Code of Conduct
* \[x] I agree to follow this project's Code of Conduct

**Comment by youanden** [comment]
@sequensucks Right now, we pass the Store header to Magento's GraphQL endpoint.

https://github.com/vuestorefront/magento2/blob/develop/packages/api-client/src/helpers/magentoLink/linkHandlers.ts#L45

In the `vcl_hash` directive, you can just put:
```
set req.hash += req.http.Store;
```

And now varnish will properly discriminate between the same graphql request.

**Comment by Frodigo** [comment]
I am assuming this is resolved.
