### ISSUE TITLE
Improve customQuery documentation

### ISSUE THREAD

**Issue by mayashavin** [vuestorefront/magento2#701]
### Provide a description of requested docs changes

The documentation for [Override queries](https://docs.vuestorefront.io/magento/guide/override-queries) is not clear and the example should be re-written to be more precise and easy to understand.

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
This has already been already released https://docs.vuestorefront.io/magento/guide/override-queries.html.
