### ISSUE TITLE
[Bug]: Duplicate environment variables in template

### ISSUE THREAD

**Issue by aapokiiso** [vuestorefront/magento2#723]
### Actual Behavior

The `.env.example` template for environment variables contains duplicates for `MAGENTO_BASE_URL`, `IMAGE_PROVIDER` and `IMAGE_PROVIDER_BASE_URL`. 

This caused some minor confusion when values had been set only to the first instances, and the empty duplicates overwrote them.

### Possible Solution

Remove the duplicate variables.

### What version of Magento 2 integration are you using?

1.0.0-rc.6

### What version of Node.js are you using?

16.14.0

### What browser (and version) are you using?

Chrome 99

### What operating system (and version) are you using?

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
This will be released in the upcoming 1.0.0-rc-.7 release
