### ISSUE TITLE
[Bug]: 'Use this address as my default one' hide the Address Box. 

### ISSUE THREAD

**Issue by jdperez128** [vuestorefront/magento2#725]
### Expected Behavior
If I logged in and I go to checkout, when I select my default shipping address and I select "Use this address as my default one" checkbox, if I click over "Select shipping method" I expect see my address selected and select the shipping method.

### Actual Behavior
If I logged in and I go to checkout, when I select my default shipping address and I select "Use this address as my default one" checkbox, if I click over "Select shipping method" the Address Box is hidden.

Only I can see the "add new address" button, if here I click over "Add new address" I don't have possibility that return for select again my default address.

### Possible Solution
Change the logic `v-if` of this box and in the case that something do click over "Add new address" we should can see one "cancel" button that allow return to select other address.

### Steps to reproduce
1. We will have do log in VSF and have one default shipping/billing address.
1. Go to the checkout
1. In the first step, click over "Continue to shipping"
1. In the Second Step, click over our Default shipping address.
1. Click over Use this address as my default one.
1. And by end click over "select shipping method"

then.. If we do click over "Add new address" we don't have possibility to return.

### What version of Magento 2 integration are you using?
2.4.3

### What version of Node.js are you using?
16.13.1

### What browser (and version) are you using?
Chrome

### What operating system (and version) are you using?
macOS

### Code of Conduct
* [x] I agree to follow this project's Code of Conduct

**Comment by bartoszherba** [comment]
@jdperez128 
This is already solved on the develop branch and will be released in 1.0.0-rc.7
