### ISSUE TITLE
[Feature]: improve performance of calls between Magento and VSF

### ISSUE THREAD

**Issue by marc-arnoult** [vuestorefront/magento2#735]
### How the project can be improved?

With a Headless Framework like **VSF**, we are making most of our calls to the e-commerce backend from NodeJS.
The **VSF** backend is more or less a _Proxy_, so in order to improve the performance we can reuse the existing connection between **VSF** and **Magento**.

### What are the acceptance criteria?

- [ ]

### Additional information

I found that every call made by **VSF** was slower than an API Client like Postman for example. 
After a few research i found that we are losing time to make a connection ( HTTPS round trip and so on... ).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
This will be released in the upcoming 1.0.0-rc.7 release.
