### ISSUE TITLE
Vetur not recognizing setup return

### ISSUE THREAD

**Issue by brunocordioli072** [vuestorefront/magento2#88]
## Expected Behavior
![image](https://user-images.githubusercontent.com/46489264/120570695-0c8b7c00-c3ef-11eb-9ba8-585943ffff00.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/46489264/120570734-21680f80-c3ef-11eb-8382-d75e0caf6b23.png)

## Possible Solution
What i did to solve this was to use @vue/composition-api defineComponent function wrapping vue template on it.
![image](https://user-images.githubusercontent.com/46489264/120570859-61c78d80-c3ef-11eb-9a12-956576d69383.png)

## Steps to Reproduce (for bugs)
Every component and pages of the application have this problem...

## Your Environment
* Version used: Using develop branch 
* Vetur version: v0.33.1

**Comment by bloodf** [comment]
Great point, I will look into that
