### ISSUE TITLE
[Bug]: Price not updated on configurable product page

### ISSUE THREAD

**Issue by marc-arnoult** [vuestorefront/magento2#880]
### Expected Behavior

Correct price from variant should be displayed for configurable product.

### Actual Behavior

Variant price is not used on the product page
<img width="1306" alt="Capture d’écran 2022-04-18 à 19 40 27" src="https://user-images.githubusercontent.com/16859411/163849700-dfc43f04-49c5-4251-8a5a-faa1473727a3.png">
.

### Possible Solution

Use the information from the variant.
```
 configurable_product_options_selection(configurableOptionValueUids: "...") {
            options_available_for_selection {
              attribute_code
              option_value_uids
            }
            media_gallery {
              disabled
              label
              position
              url
            }
            variant {
              uid
              sku
              name
              // ------- There --------------
              price_range {
                maximum_price {
                  final_price {
                    currency
                    value
                  }
                  regular_price {
                    currency
                    value
                  }
                }
                minimum_price {
                  final_price {
                    currency
                    value
                  }
                  regular_price {
                    currency
                    value
                  }
                }
              }
            }
```

### Steps to reproduce

- Go on a configurable product page.
- Change the selection to be redirected on the correct variant.

### What version of Magento 2 integration are you using?

2.4.3

### What version of Node.js are you using?

16

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
It has been already fixed.
