### ISSUE TITLE
Adjust file source MyProfile to MyProfile.vue in MyAccount.vue

### ISSUE THREAD

**Issue by jonasvanderhaegen** [vuestorefront/magento2#90]
In develop branch at step 8 when running yarn dev:theme file I got error message "file was not found" in a nutshell.
 
in packages/theme/pages/MyAccount.vue on line 50

import MyProfile from './MyAccount/MyProfile';

should be changed to 

import MyProfile from './MyAccount/MyProfile.vue';

**Comment by bloodf** [comment]
@jonasvanderhaegen fixed :)
