### ISSUE TITLE
[ERROR]: Cannot connect to shop

### ISSUE THREAD

**Issue by falko100** [vuestorefront/magento2#944]
When trying to connect the vue-storefront to my Magento 2.4 shop I'm getting an error.
I did the config changes in `config/dev.json` and have an `.env` containing only `STORE_ENV=dev`
I setup the language to match my store view: 
<img width="178" alt="image" src="https://user-images.githubusercontent.com/11974977/152970185-d14965c9-8537-4183-b026-3e322a274280.png">

![image](https://user-images.githubusercontent.com/11974977/152970351-7b0f159c-08c2-4004-b08f-1f604f91f99c.png)

But I still get this error:
```
ERROR  [VSF][error]:  [GraphQL error]: Message: Requested store is not found, Path: undefined
ERROR  [VSF][error]:  [Network error]: ServerError: Response not successful: Received status code 500
ERROR  [VSF][error]:  useProduct/newProducts/search Cannot read properties of undefined (reading 'products')
```

Any tips on connecting / finding where these errors occur so I can do some debugging?

**Comment by Frodigo** [comment]
I suppose it has already been fixed.
